### PR TITLE
Portuguese translation (pt_PT) update

### PR DESCRIPTION
**Pull request by pedro-mendonca**

### CODE REVIEW

**Review by GaryJones — APPROVED** [review]

**Comment by jrfnl** [comment]
Thank you for this update. The PR unfortunately will need to be rebased (and squashed) before I can merge it. Would you like to do this yourself or shall I do it for you ?

**Comment by pedro-mendonca** [comment]
Done.
Wait until tomorrow, I'll probably add some more changes that I've found yesterday but had no time to push it. I'll let you know when it's complete.

**Comment by jrfnl** [comment]
@pedro-mendonca Ok, will do. Thank you for your quick response.

**Comment by pedro-mendonca** [comment]
Hi @jrfnl 
You can merge now, pt_PT full reviewed 👍

**Comment by jrfnl** [comment]
@pedro-mendonca Okidoki. Thanks again!

**Pull request merged**
