### PR TITLE
Added git ignorance file

### PR DESCRIPTION
**Pull request by shivapoudel**
Configured for Different Editors, OS X metadata and Windows Junk xD

### CODE REVIEW

**Comment by GaryJones** [comment]
Folks really should have these setup as global gitignores on their own system, so I'm *meh* about having this. I'd rather it was just used to ignore project-related files, which we may not have any yet.

**Comment by shivapoudel** [comment]
We can understand but this is for those for those folks we are unknown about global ignorance of project related files. For eg: #348 has submit the `.idea/misc.xml` file accidently :sweat_drops:

**Comment by GaryJones** [comment]
I guessed where the inspiration comes from, but really, they should fix it once in their own system, than all of the repos containing code to ignore files that some people will never have (i.e. as a Mac user, I'm never going to be submitting Windows' Thumbs.db in PRs; I don't use Netbeans, so that line is redundant too).

**Comment by jrfnl** [comment]
@shivapoudel FYI - You may find this article interesting to read:
http://365git.tumblr.com/post/519016351/three-ways-of-excluding-files

I have global .gitignore file with persistent thing set up and per project I may ignore some specific files which I add to /.git/info/excludes

**Pull request closed without merging**
