### PR TITLE
Add update mode

### PR DESCRIPTION
**Pull request by swiderski**
I am n00b, too much working alon... but I removed files of IDE, added gitignore, and merged with current develop version. Hope this time will be OK.

### CODE REVIEW

**Comment by GaryJones** [comment]
Thanks.

Unmergeable, due to a conflict. The class file shows `2,709 additions, 2,218 deletions not shown`, which probably indicates that your file is indenting with spaces instead of the tabs that we switched to as per WP coding standards. 

You'll need to fork from `develop`, and manually add the changes in - simply copying and pasting your complete class file won't work.

**Comment by GaryJones** [comment]
Ideally, all of the changes will be squashed too, so that we don't have multiple commits for the same thing.

**Comment by swiderski** [comment]
I pass. Maybe someone else will want to do it. 

I did these merges for three days, and people ask for these feature for more then an year. I understand you want to force on me good Git practices, but I also see you are not very interested in making any extra step to see those 10 places where files differ now(except for white spaces), as I made merge with most current develop version(to make it as easy as I can for you). 
I did every Merge using WinMerge tool, and it took me 10 minutes to add all your changzes.

You can ignore my or duckzland contribution, just add that code finally :-)

**Comment by GaryJones** [comment]
What the original changes made against 2.4.0? If so, point me to a gist of your complete amended 2.4.0 class file and I'll see if I can find the changes from there.

**Comment by swiderski** [comment]
http://themeforest.net/forums/thread/modified-tgm-plugin-added-option-to-update-the-plugins/105830 this is the topic where it could be first found. It was made on 2.3.6
File: http://pastebin.com/0jh83Xmw

I made whole merge for you, if you can just turn on ignoring of whithspace you will get all on your plate. 

I will try one last time to submit you corrected version with proper whitspace.

With regards.

**Comment by swiderski** [comment]
OK, can you check is it better now? For me it shows only actual code changes, white spaces and end lines are correct now.

**Comment by swiderski** [comment]
Sorry, still some white space smaller glitches. Will fix in few mins.

**Comment by swiderski** [comment]
Done. If I have to make another pull request then please tell me. I checked and it only allows me to view current one, so hopefully you see all the changes. Sorry for my earlier anger.

**Comment by jrfnl** [comment]
@swiderski I've just had a good look at this and this is going wrong as you're still trying to merge a branch based on `master` not on `develop` into `develop`.

Try a PR based `duckzland/develop` (where I se you've applied the changes too) to `tgmpa/develop`. That should hopefully give a proper diff.

**Comment by swiderski** [comment]
I am getting lost with this:-) Will try.

**Comment by swiderski** [comment]
OK done, there is new pull request, and it even allow auto merge!

**Comment by GaryJones** [comment]
A version has now been merged into the `develop` branch. See #381.

**Pull request closed without merging**
