### PR TITLE
Fixed errors in es_ES strings

### PR DESCRIPTION
**Pull request by nilovelez**

### CODE REVIEW

**Review by jrfnl — APPROVED** [review]

**Comment by GaryJones** [comment]
I was just getting someone else to give these a check over, before merging :-)

**Comment by jrfnl** [comment]
@GaryJones Sorry about that! If that would yield changes, update via a follow-on PR ? I looked it over myself and the Spanish looked good to me, but I'm not a native speaker.

**Comment by nilovelez** [comment]
@jrfnl I am a native speaker.

My PR only included only some minor corrections, I made most of the changes to adapt the translation to the es_ES translation team guidelines

https://es.wordpress.org/colabora/traducciones/guia-de-traductores/

**Comment by GaryJones** [comment]
My checker said it was all good too :-)

**Pull request merged**
