### PR TITLE
[Master] Fix: multisite admin menu and notices

### PR DESCRIPTION
**Pull request by jrfnl**
As on multisite by default plugins can only be installed from the network admin, it makes more sense showing the TGM page in the network admin and not in the site admin.

On that same note, the admin notices should be shown on the network admin too.

Related #228, #239

Sister-PR to PR #247

### CODE REVIEW

**Comment by jrfnl** [comment]
On second though: This should not be merged as is. The logic is valid for TGM being included with a plugin, however, when TGM is enabled for a theme, the logic does not hold.

The problem then is that when on multisite:
- The theme used is site-specific, so whether TGM is active will differ per site.
- However plugins can normally only be installed from the network admin and not every site-admin has access to the network admin, which causes an issue.
- Similarly, as the theme loaded when on the network admin is the theme associated with site 1, it will be difficult to detect when to show a network admin a notice about installing plugins via TGM needed for themes in use by child-sites other than site 1.

**Comment by Daronspence** [comment]
Is this problem going to be addressed? Or are MU users SOL?

**Comment by jrfnl** [comment]
@Daronspence This will be addressed and probably quite soon too.

**Comment by Daronspence** [comment]
@jrfnl I've used the `$ms_hook` variable you defined in one of your commits and it seems to be working nicely for my needs. I've got the class semi-heavily customized at this point so it's not a huge deal for me at this point, though I'm sure it would certainly benefit others!

**Pull request closed without merging**
