### PR TITLE
Remember the page hook for the admin page

### PR DESCRIPTION
**Pull request by jrfnl**
This enables the theme/plugin which incorporates this plugin to hook actions into the specific page hook (lean loading).

### CODE REVIEW

**Comment by thomasgriffin** [comment]
Would you mind creating this pull request against the `master` branch? I've not done anything with the `develop` branch in a while. Indeed, I need to actually remove it as it doesn't quite make sense for this repo.

**Comment by jrfnl** [comment]
Hi @thomasgriffin, will do for all my PRs. I'll send them in later today.

All the same, I actually went through all the commits in between develop and master yesterday and most of them make a lot of sense. Maybe develop should be merged with master and then removed ?

**Comment by jrfnl** [comment]
@thomasgriffin If it helps, I have a branch in my fork which incorporates the develop branch & all my open pull requests which I've been using for testing.

https://github.com/jrfnl/TGM-Plugin-Activation/tree/Develop-CPR

**Comment by jrfnl** [comment]
@thomasgriffin Oh and on another note, would you be open to some boyscouting ? I'm quite happy to do a quick codestyle review based on the WP coding standards and set up the travis hook to auto-test new PRs. Let me know if you'd welcome that.

**Comment by jrfnl** [comment]
@thomasgriffin Done x 5

**Pull request merged**
