### PR TITLE
Add Scrutinizer config file

### PR DESCRIPTION
**Pull request by GaryJones**
https://scrutinizer-ci.com

Tested against a fork of this repo (resulting suggestions to be applied later on) so will work when this repo is hooked up too.

### CODE REVIEW

**Comment by jrfnl** [comment]
Is there anything we can do about the 'else on same line as brace from previous if' ? It's not part of the official WPCS and having it on the next line make for easier to read code.

**Comment by GaryJones** [comment]
> Is there anything we can do about the 'else on same line as brace from previous if' ? It's not part of the official WPCS and having it on the next line make for easier to read code.

It should be `} else {` as it is [part of the standard](https://make.wordpress.org/core/handbook/coding-standards/php/#brace-style). Scrutinizer does have a check for it, so we should be matching WPCS, i.e. your
```
}
else {
```
are not correct.

**Comment by jrfnl** [comment]
> It should be } else { as it is part of the standard. 

Just read through it again and no, it does not say that. All it says is that braces should be used (rightfully so), not whether the else *should* be on the same or the next line.

**Comment by shivapoudel** [comment]
@jrfnl IMO having `} else {` look pretty good rather than your's 
```
}
else {
```

**Comment by GaryJones** [comment]
It does say that: "Braces shall be used for all blocks *in the style* shown here". All the examples on that page use it, and most, if not all instances in WP core use it. It may not explicitly say "Put the `}` on the same line as the `else {`, but it's a fairly standard to use the One True Brace Style (variant of K&R) in WP. PSR-2 is the same for control structures.

**Comment by jrfnl** [comment]
@GaryJones Darn, did I really read over that bit ? Ok, never mind, the standard it is. Just weirdly inconsistent with the rest of the standard (less whitespace while most of the standard goes for more whitespace).

@shivapoudel I didn't say anything about looking 'pretty/good'. My point was about ease of readability.

**Comment by jrfnl** [comment]
@GaryJones oh and are you happy with the resulting scrutinizer behaviour ? I.e. can I merge ?

**Comment by GaryJones** [comment]
Merge as is please - we can pick up issues about code style or other config tweaks later on.

**Pull request merged**
