### PR TITLE
updated the es_ES translation

### PR DESCRIPTION
**Pull request by nilovelez**
Translated some pending string from the es_ES translation

### CODE REVIEW

**Review by jrfnl — APPROVED** [review]

**Comment by jrfnl** [comment]
Thank you very much @nilovelez. I will merge this in a few days once I've fixed the build failure (unrelated to your PR so nothing for you to worry about)

**Comment by jrfnl** [comment]
Hi @nilovelez Thank you for your patience. The issues with the build are now fixed. Could you please rebase your PR on the current `develop` branch ? Thanks!

**Comment by nilovelez** [comment]
ready to go

**Comment by jrfnl** [comment]
Excellent! Thank you very much.

**Pull request merged**
