### PR TITLE
[Develop] Allow other plugins to filter the action links similar to WP Core.

### PR DESCRIPTION
**Pull request by jrfnl**

### CODE REVIEW

**Comment by jrfnl** [comment]
@thomasgriffin Thanks for your response. I've changed the PR to reflect your remark. All the same, the only reason I did it that way is to stay in line with the WP core handling of the same.

**Comment by thomasgriffin** [comment]
Would you mind creating this pull request against the master branch? I've not done anything with the develop branch in a while. Indeed, I need to actually remove it as it doesn't quite make sense for this repo.

**Comment by GaryJones** [comment]
> Indeed, I need to actually remove it as it doesn't quite make sense for this repo.

@thomasgriffin Why are you planning to remove the develop branch? That's a really bad decision IMO.

**Comment by GaryJones** [comment]
+1 to the filter.

**Comment by jrfnl** [comment]
> @thomasgriffin Why are you planning to remove the develop branch? That's a really bad decision IMO.

@GaryJones Not just your HO, I concur.

**Comment by GaryJones** [comment]
I'd prefer to see the hooks named as `tgmpa_plugin_action_links` and `tgmpa_network_admin_pugin_action_links`.

This follows the [core convention](https://github.com/WordPress/WordPress/blob/ce6c00f1409c8d9f01f4e13c1085c05d928f1069/wp-admin/includes/class-wp-plugins-list-table.php#L460) for naming of those action links hooks, but with our prefix before it, and consistently using underscores.

**Comment by jrfnl** [comment]
@GaryJones The original commit literally followed what core did, @thomasgriffin's however didn't agree...

**Comment by GaryJones** [comment]
I know, and #300 is a slightly more correct variation (order of prefixes, interpolation) on what you proposed. If you agree, then merge it.

Closing in favour of #300.

**Comment by jrfnl** [comment]
I agree & merged.

**Pull request closed without merging**
