### PR TITLE
Add fr_CA copied from fr_FR + minor corrections.

### PR DESCRIPTION
**Pull request by ghost**
Our production use fr_CA, it was easy to add it by copying the existing fr_FR.
I have added a few minor corrections that are not locale specific, so I have updated fr_FR too.

ps : TGMPA is great tool, helped streamline our installation process, thanks for that!

### CODE REVIEW

**Comment by ghost** [comment]
I have added another set of corrections instead of submitting another pull request.
The second set of corrections could benefit from a review from other french users of TGM.

**Comment by ghost** [comment]
Sorry for the multiple submit. I'll wait for review before doing other changes.

**Review by jrfnl — CHANGES_REQUESTED** [review]
Hi @eric-gagnon Sorry that it took us a while before anyone looked at this PR. Thank you so much for contributing this translation and improving the `fr_FR` one!

Could you please fix the filenames so they are in line with the other translation files in the `languages` directory ? The `fr_FR` files are now seen as new files, instead of updates of existing files.

The file names should be `tgmpa-fr_FR.po/mo` and `tgmpa-fr_CA.po/mo`.

Other than that: You indicated that a review by a native French speaker would be recommended. We don't have anyone available to review the actual translations, so if you know of someone you could ask yourself, please do!

**Comment by plateforme-medialab-responsables** [comment]
I will check the filename.

I was maybe imprecise. I'm actually french native but from Quebec. The revision was done by our linguistic service at Bibliothèque et archives nationales du québec (http://www.banq.qc.ca/) so you can have a good assurance that it's high quality.

What I meant by french reviewer was more french from France as there could be different terminology choices (also ponctuation can differ).

I will double check the changes that I think could be worth discussing and otherwise you could let it pass as base fr_CA. If someone is available for fr_FR later, they could review our changes to see if it's worth merging back.

**Comment by ghost** [comment]
I will check the filename.

I was maybe imprecise. I'm actually french native but from Quebec. The revision was done by our linguistic service at Bibliothèque et archives nationales du québec (http://www.banq.qc.ca/) so you can have a good assurance that it's high quality.

What I meant by french reviewer was more french from France as there could be different terminology choices (also ponctuation can differ).

I will double check the changes that I think could be worth discussing and otherwise you could let it pass as base fr_CA. If someone is available for fr_FR later, they could review our changes to see if it's worth merging back.

**Comment by ghost** [comment]
I have deleted my fork this morning, I forgot about my pull request sorry.
I will try to recover following the procedure here : https://stackoverflow.com/questions/20977530/recover-a-commit-sent-as-a-pull-request-from-a-deleted-fork-on-github

**Comment by ghost** [comment]
I was able to recover the pull request following the procedure but I prefer to not break things further,  I did a new pull request : https://github.com/TGMPA/TGM-Plugin-Activation/pull/734

You can close / decline this one.

**Pull request closed without merging**
