### PR TITLE
Update Feature (was Develop)

### PR DESCRIPTION
**Pull request by swiderski**
Update feature! 
Hopefully this time I will do it right.

### CODE REVIEW

**Comment by duckzland** [comment]
Hi guys, is this going to be implemented anytime soon? Thanks

**Comment by GaryJones** [comment]
@jrfnl has looked through the code, but found several issues with it:

- bulk update on installed plugin without update will re-install
- pre-packaged update via link, says the plugin has updated, but in reality it hasn't
- repo found updates are not shown nor taken into account

So, yes, while this feature will probably get into the 2.5.0 release, it needs implementing properly in a way that we'd be happy.

This ticket will be closed once the new PR has been created.

**Comment by duckzland** [comment]
ok thanks for the info, and I think at this rate its better if you develop your own version on how to update this plugin. it is a nightmare to keep up with the mainstream repo

**Comment by jrfnl** [comment]
@duckzland I'm working on integrating your code and have just send in #368 to actually make integrating the update feature a lot simpler - with graceful thanks for all the hard work you've done on this!

**Comment by duckzland** [comment]
@jrfnl If possible you could take a look at my master branch, I've clean out a bit the code and now the updating and install will have 2 different set of page, each page will list only plugin related to be updated and / or installed. I really believe at this development pace, it is better if the collaborator to do the integration, will result in much cleaner code imo.

**Comment by jrfnl** [comment]
@duckzland I will - I've got your fork as one of the remotes for my local version atm ;-)

**Comment by swiderski** [comment]
@duckzland - so is there any help needed any more, or now we just wait?

**Comment by GaryJones** [comment]
Just wait :-) #368 is going in shortly, followed by some abstraction-related PRs to reduce duplicate code, then we have a cleaner code base to add new features like updates :-)

**Comment by duckzland** [comment]
@swiderski I think just as gary said, better wait till the chaos finish and we can try to test and sort out bugs :)

**Comment by jrfnl** [comment]
@duckzland @swiderski With a bit of luck, I'll have something for you to test some time tomorrow. Fingers crossed.

**Comment by jrfnl** [comment]
> now the updating and install will have 2 different set of page, each page will list only plugin related to be updated and / or installed.

@duckzland Where can I find that code ? I've done compares based on Duckzland-update-branch/add_update_mode and on https://github.com/duckzland/TGM-Plugin-Activation/commit/abc28dbcfb04bb8fc1fdc53c11c00ef6750aa5de which is the last usable one I can do a compare on.
In the next commit you seem to have changed the code style completely away from the WordPress standard which makes a compare impossible, let alone any possibility of future merges.

**Comment by duckzland** [comment]
@jrfnl it is in the master branch the add_update_mode is based on the 2.4.x branch while the master branch is based on the 2.5.x branch.

**Comment by jrfnl** [comment]
@duckzland Will have a look, but seriously - why make it so difficult ?

**Comment by duckzland** [comment]
@jrfnl sorry wasnt intended to make things difficult for you.

**Comment by jrfnl** [comment]
@duckzland not just me, you're going to have a hell of a job if you ever want to be able to pull the changes from this plugin into your fork again.

**Comment by duckzland** [comment]
@jrfnl oh this fork is temporary fix only since I got themes that need to be released asap, once you got this feature in mainstream I'm going to remove the fork :) no need for forking if mainstream has it.

**Comment by swiderski** [comment]
IF you like I can make some merge and switching back to proper Wordpress coding style. It wont take more then 10 minutes with PHPStorm. Just tell me what you need exactly.

**Comment by duckzland** [comment]
@swiderski its cool by me :) maybe create a new branch based on master? or you can coordinate with jrfnl for whatever best for her :)

**Comment by jrfnl** [comment]
@swiderski Don't bother. I'm implementing that bit quite differently anyhow. $mode is only available since 4.1 and I don't see any need to make the minimum requirement for TGMPA 4.1 at this moment.

**Comment by GaryJones** [comment]
A version has been merged into the `develop` branch. See #381.

**Pull request closed without merging**
