### PR TITLE
Configure .editorconfig for IDE

### PR DESCRIPTION
**Pull request by shivapoudel**
@GaryJones this not work very well:

```
[{*.md,*.yml}]
```

Usually works with full names like:

```
[{README.md,.coveralls.yml,.etc.yml}]
```

I'm using with VIM and Sublime and does not work. Impossible to use something unstable only for satisfaction of saving three lines in a configuration file.
;)

### CODE REVIEW

**Comment by GaryJones** [comment]
I'm only going by what I see on http://develop.svn.wordpress.org/trunk/.editorconfig .

Try `[*.{md,yml}]` instead, as that's the example given on http://editorconfig.org/

**Comment by GaryJones** [comment]
Thanks @shivapoudel!

**Comment by shivapoudel** [comment]
Markdown `trim_trailing_whitespace` should be false xD

For instance: We have Lead Developer and there at the end we have added the trailing whitespace for newline trick ;)

**Comment by GaryJones** [comment]
I know. My ST3 is already setup with custom rules for .md files :-)

When I commented, it was against a line that said no newline at the end of the file, not trimming whitespace at the end of the line.

**Comment by shivapoudel** [comment]
xD

**Pull request merged**
