### PR TITLE
Fix the comments from example.php array

### PR DESCRIPTION
**Pull request by awps**
Make it easier to uncomment the $config['strings']. I don't see a single reason why not use this comment style(`//?` instead `/* ? * /`).

### CODE REVIEW

**Review by jrfnl — APPROVED** [review]
Makes sense to me.

**Comment by jrfnl** [comment]
@Smartik89 The travis error had nothing to do with your PR and has been fixed in the mean time. Would you mind rebasing the PR so we can get a passing build & can merge this in ? Thanks!

**Comment by jrfnl** [comment]
For lack of response, I've rebased the PR to get the build to pass.

**Review by GaryJones — APPROVED** [review]

**Comment by GaryJones** [comment]
Good to go.

**Pull request merged**
